### ISSUE TITLE
Link youtube

### ISSUE THREAD

**Issue by ecoelhor** [TiagoSansao/Happy-NLW-03#2]
Oi Tiago, 
alguma change de ainda ter os links da semana dos videos do youtube. Acompanhei a primeira aula, mas tive uma revira-volta aqui e nao consegui mais assistir. Hoje nao consigo mais accesso pelo link dos emails.
Att,

**Comment by TiagoSansao** [comment]
Boa tarde, infelizmente não, @ecoelhor.
A NLW tem a duração de apenas uma única semana, após ela acabar, todo conteúdo é removido.
